server:
  port: 8085

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/BANRAKAS_MESSAGING_APP
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"